name: Test by Firebase Emulator on PR
"on": pull_request
env:
  API_KEY: ${{ secrets.API_KEY }}
  AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
  MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
  APP_ID: ${{ secrets.APP_ID }}
  MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
  FIREBASE_AUTH_EMULATOR_HOST: ${{ secrets.FIREBASE_AUTH_EMULATOR_HOST }}
  FIRESTORE_EMULATOR_HOST: ${{ secrets.FIRESTORE_EMULATOR_HOST }}
  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npx shadow-cljs compile app
          start: npm run emulators:test, npx shadow-cljs start
          wait-on: "http://localhost:8081, http://localhost:8080"
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
