name: Test by Firebase Emulator on PR
"on": pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: "${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: "${{ runner.os }}-node-modules-"
      - name: Use Cache Shadow Cljs
        uses: actions/cache@v2
        with:
          path: .shadow-cljs
          key: "${{ runner.os }}-shadow-cljs-${{ hashFiles('**/shadow-cljs.edn') }}"
          restore-keys: "${{ runner.os }}-shadow-cljs-"
      - name: Use Cache Firebase Emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators/
          key: "${{ runner.os }}-firebase-emulators-${{ hashFiles('**/firebase.json') }}"
          restore-keys: "${{ runner.os }}-firebase-emulators-"
      - name: Install Dependencies
        run: npm install
      - name: Run Firebase Emulator
        run: npm run emulators-test &
      - name: Run Test
        run: npm run test
        env:
          API_KEY: "${{ secrets.API_KEY }}"
          AUTH_DOMAIN: "${{ secrets.AUTH_DOMAIN }}"
          PROJECT_ID: "${{ secrets.PROJECT_ID }}"
          STORAGE_BUCKET: "${{ secrets.STORAGE_BUCKET }}"
          APP_ID: "${{ secrets.APP_ID }}"
          MEASUREMENT_ID: "${{ secrets.MEASUREMENT_ID }}"
          FIREBASE_AUTH_EMULATOR_HOST: "${{ secrets.FIREBASE_AUTH_EMULATOR_HOST }}"
          FIRESTORE_EMULATOR_HOST: "${{ secrets.FIRESTORE_EMULATOR_HOST }}"
          GCLOUD_PROJECT: "${{ secrets.GCLOUD_PROJECT }}"
